### ISSUE TITLE
[KubeGems-v1.22.0] Enable Jaeger SPM 

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#140]
Jaeger UI 在 1.33后开启了Service Performance Monitoring的特性支持（实验性质）

**数据源实现**
通过 OpenTelemetry Collector 在收集 Trace 数据时， 调用 [spanmetricsprocessor](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor#section-readme) 来处理 span 上下文中的应用性能数据，并将其写入到 exporter
![image](https://user-images.githubusercontent.com/2688646/177541416-5c30c0ec-1b81-426a-be6f-539cd8c27c55.png)

KubeGems 在 OpenTelemetry Collector 中仅需要简单配置即可开启功能

```
    exporters:
      prometheusremotewrite:
        endpoint: "http://kube-prometheus-stack-prometheus.kubegems-monitoring:9090/api/v1/write"
        external_labels:
          source: opentelemetry
    processors:
      spanmetrics:
        metrics_exporter: prometheusremotewrite
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_http:
            endpoint: 0.0.0.0:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      pipelines:
        traces:
          exporters:
          - jaeger
          - prometheusremotewrite
          processors:
          - spanmetrics
          receivers:
          - otlp
          - jaeger
          - zipkin
```
