### ISSUE TITLE
tke-gpu-manager can't regist device if container runtime is containerd.

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#155]
What did you do?
enable tke-gpu-manager plugin on kubegems admin page

What did you expect to see?
gpu devices  regist in kubernetes cluster witch enable tke-gpu-manager plugin

What did you see instead? Under which circumstances?

```
Capacity:
  cpu:                48
  ephemeral-storage:  228121004Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             131878364Ki
  pods:               110
Allocatable:
  cpu:                48
  ephemeral-storage:  210236316939
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             131775964Ki
  pods:               110
```

Environment

```
Kubegems version:
v1.21.0

Kubernetes version:
v1.23.8
```

**Comment by LinkMaq** [comment]
if node runtime is containerd, we should be inject this enviroments in gpu-manager

```
    spec:
      containers:
        - name: EXTRA_FLAGS
          value:  --container-runtime-endpoint=/var/run/containerd/containerd.sock
        image: registry.cn-beijing.aliyuncs.com/kubegems/gpu-manager:v1.1.5
        imagePullPolicy: IfNotPresent
```
