### ISSUE TITLE
Prometheus query of redis results are infinite

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#266]
**What did you do?**

Too much redis alert message which is  memory full
![image](https://user-images.githubusercontent.com/2688646/192929267-9d9caa5c-58c3-493f-8efd-60888381b0df.png)

The default alertrule of redis query out of range, if `redis_memory_max_bytes` has none data
 ```
  - name: RedisMemoryHigh
    rules:
    - alert: RedisMemoryHigh
      annotations:
        message: Redis [namespace {{"{{"}} $labels.namespace }}] [service {{"{{"}} $labels.service
          }}] [instance {{"{{"}} $labels.instance }}] is using too much memory
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: redis_memory_used_bytes{service="{{ template "prometheus-redis-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}
        / redis_memory_max_bytes{service="{{ template "prometheus-redis-exporter.fullname" . }}", namespace="{{ .Release.Namespace }}"}
        * 100>90
      for: 2m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: RedisMemoryHigh
        gems_namespace: {{ .Release.Namespace }}
        severity: error
```
**What did you expect to see?**

set max percentage `100` like this,

```
      expr: redis_memory_used_bytes{service="{{ template "prometheus-redis-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}
        / redis_memory_max_bytes{service="{{ template "prometheus-redis-exporter.fullname" . }}", namespace="{{ .Release.Namespace }}"}
        * 100>90<=100
```

**Environment**

* System information:

	  Ubuntu20.04.1

* Kubegems version:

        v1.22.0-beta.1

* Kubernetes version:

        1.21.10
