### ISSUE TITLE
Modify OpenTelemetry configurations based on KubeGems metadata

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#313]
KubeGems metadata now:

```
  "app": "<service_name>",
  "cluster": "<cluster_name>",
  "container": "<container_name>",
  "environment": "<environment_name>",
  "image": "<image_name>:<tag_name>",
  "namespace": "<namespace_name>",
  "node": "<node_name>",
  "pod": "<pod_name>,
  "project": "<project_name>",
  "tenant": "<tenant_name>",
  "version": "<version>"
```
So, to enable unified federated queries, all of our labels need to follow the same rules.

- [x] opentelemetry.config should be changed

```
    processors:
      batch: {}
      k8sattributes:
        passthrough: true
      memory_limiter:
        check_interval: 5s
        limit_mib: 1638
        spike_limit_mib: 512
      spanmetrics:
        dimensions:
        - name: namespace
        - name: pod
        - name: http.status_code
        dimensions_cache_size: 2000
        latency_histogram_buckets:
        - 1ms
        - 10ms
        - 100ms
        - 500ms
        - 1s
        - 10s
        metrics_exporter: prometheusremotewrite
```
- [x] recording rule from span

```
  groups:
  - name: opentelemetry-collector
    rules:
    - expr: |
        sum(label_replace(label_replace(label_replace(calls_total, "namespace", "$1", "k8s_namespace_name", "(.*)"), "service", "$1", "service_name", "(.*)"), "pod", "$1", "k8s_pod_name", "(.*)"))without(k8s_namespace_name, k8s_pod_name, service_name)
      record: gems_otel_calls_total
    - expr: |
        sum(label_replace(label_replace(label_replace(latency_bucket, "namespace", "$1", "k8s_namespace_name", "(.*)"), "service", "$1", "service_name", "(.*)"), "pod", "$1", "k8s_pod_name", "(.*)"))without(k8s_namespace_name, k8s_pod_name, service_name)
      record: gems_otel_latency_bucket
```

- [x] OpenTelemetry Env inject

```
spec:
  template:
    spec:
      containers:
        - name: application
          env:
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app']
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: >-
                service.name=$(OTEL_SERVICE_NAME),namespace=$(OTEL_K8S_NAMESPACE),node=$(OTEL_K8S_NODE_NAME),pod=$(OTEL_K8S_POD_NAME)
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.observability:4317
```
