### ISSUE TITLE
Opentelemetry some metrics type switch between Counter and Guage

### ISSUE THREAD

**Issue by jojotong** [kubegems/kubegems#339]
```log
kubectl logs -n observability opentelemetry-collector-59fc57bd46-gn9wc
2022-12-09T06:20:26.594Z        error   prometheusexporter@v0.66.0/log.go:34    error gathering metrics: 51 error(s) occurred:
* collected metric kafka_consumer_connection_count label:<name:"client_id" value:"consumer-sync_roc_userInfo_groupid-8" > label:<name:"container_id" value:"e1909a339c4f8ab242f91fdbaeefe5e30147e1d459823c27e9144158fb2b04be" > label:<name:"host_arch" value:"amd64" > label:<name:"host_name" value:"stable-rdp-operation-service-6ccf4b7d95-vnphw" > label:<name:"job" value:"rdp-operation-service" > label:<name:"kafka_version" value:"2.5.1" > label:<name:"namespace" value:"harix-rdp-cloudpepper-v3-dit" > label:<name:"node" value:"l-172016023089-ops.cloudminds.com" > label:<name:"os_description" value:"Linux 4.15.0-65-generic" > label:<name:"os_type" value:"linux" > label:<name:"pod" value:"stable-rdp-operation-service-6ccf4b7d95-vnphw" > label:<name:"process_command_line" value:"/usr/local/jdk1.8.0_351/jre/bin/java -Xms1G -Xmx1G -javaagent:/opt/otel/opentelemetry-javaagent.jar" > label:<name:"process_executable_path" value:"/usr/local/jdk1.8.0_351/jre/bin/java" > label:<name:"process_pid" value:"198" > label:<name:"process_runtime_description" value:"Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.351-b10" > label:<name:"process_runtime_name" value:"Java(TM) SE Runtime Environment" > label:<name:"process_runtime_version" value:"1.8.0_351-b10" > label:<name:"service_name" value:"rdp-operation-service" > label:<name:"spring_id" value:"kafkaConsumerFactory.consumer-sync_roc_userInfo_groupid-8" > label:<name:"telemetry_auto_version" value:"1.20.2" > label:<name:"telemetry_sdk_language" value:"java" > label:<name:"telemetry_sdk_name" value:"opentelemetry" > label:<name:"telemetry_sdk_version" value:"1.20.1" > counter:<value:2 >  should be a Gauge
* collected metric kafka_producer_response_total label:<name:"client_id" value:"producer-1" > label:<name:"container_id" value:"e150a74d862a859d256217eb0d414e1db0f55bfa5e477a08fd047681609a9db1" > label:<name:"host_arch" value:"amd64" > label:<name:"host_name" value:"stable-harix-skill-vision-86ddbc57b5-pxwqk" > label:<name:"job" value:"harix-skill-vision" > label:<name:"namespace" value:"harix-cloudpepper-v3-dit" > label:<name:"node" value:"l-172016023084-ops.cloudminds.com" > label:<name:"node_id" value:"node-0" > label:<name:"os_description" value:"Linux 4.15.0-66-generic" > label:<name:"os_type" value:"linux" > label:<name:"pod" value:"stable-harix-skill-vision-86ddbc57b5-pxwqk" > label:<name:"process_command_line" value:"/usr/local/jdk1.8.0_351/jre/bin/java -ea -Djava.security.egd=file:/dev/urandom -Xms4G -Xmx4G -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:MaxTenuringThreshold=1 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=utf-8 -javaagent:/opt/otel/opentelemetry-javaagent.jar" > label:<name:"process_executable_path" value:"/usr/local/jdk1.8.0_351/jre/bin/java" > label:<name:"process_pid" value:"35" > label:<name:"process_runtime_description" value:"Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.351-b10" > label:<name:"process_runtime_name" value:"Java(TM) SE Runtime Environment" > label:<name:"process_runtime_version" value:"1.8.0_351-b10" > label:<name:"service_name" value:"harix-skill-vision" > label:<name:"telemetry_auto_version" value:"1.20.2" > label:<name:"telemetry_sdk_language" value:"java" > label:<name:"telemetry_sdk_name" value:"opentelemetry" > label:<name:"telemetry_sdk_version" value:"1.20.1" > gauge:<value:1.315895e+06 >  should be a Counter
* collected metric kafka_producer_request_total label:<name:"client_id" value:"producer-1" > label:<name:"container_id" value:"e150a74d862a859d256217eb0d414e1db0f55bfa5e477a08fd047681609a9db1" > label:<name:"host_arch" value:"amd64" > label:<name:"host_name" value:"stable-harix-skill-vision-86ddbc57b5-pxwqk" > label:<name:"job" value:"harix-skill-vision" > label:<name:"namespace" value:"harix-cloudpepper-v3-dit" > label:<name:"node" value:"l-172016023084-ops.cloudminds.com" > label:<name:"node_id" value:"node-2" > label:<name:"os_description" value:"Linux 4.15.0-66-generic" > label:<name:"os_type" value:"linux" > label:<name:"pod" value:"stable-harix-skill-vision-86ddbc57b5-pxwqk" > label:<name:"process_command_line" value:"/usr/local/jdk1.8.0_351/jre/bin/java -ea -Djava.security.egd=file:/dev/urandom -Xms4G -Xmx4G -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:MaxTenuringThreshold=1 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=utf-8 -javaagent:/opt/otel/opentelemetry-javaagent.jar" > label:<name:"process_executable_path" value:"/usr/local/jdk1.8.0_351/jre/bin/java" > label:<name:"process_pid" value:"35" > label:<name:"process_runtime_description" value:"Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.351-b10" > label:<name:"process_runtime_name" value:"Java(TM) SE Runtime Environment" > label:<name:"process_runtime_version" value:"1.8.0_351-b10" > label:<name:"service_name" value:"harix-skill-vision" > label:<name:"telemetry_auto_version" value:"1.20.2" > label:<name:"telemetry_sdk_language" value:"java" > label:<name:"telemetry_sdk_name" value:"opentelemetry" > label:<name:"telemetry_sdk_version" value:"1.20.1" > gauge:<value:2.5212291e+07 >  should be a Counter
        {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.66.0/log.go:34
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
        github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/http.go:139
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2109
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2487
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
        go.opentelemetry.io/collector@v0.66.0/config/confighttp/compression.go:162
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2109
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.36.4/handler.go:204
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
        go.opentelemetry.io/collector@v0.66.0/config/confighttp/clientinfohandler.go:39
net/http.serverHandler.ServeHTTP
        net/http/server.go:2947
net/http.(*conn).serve
        net/http/server.go:1991
```

opentelemetry config:
```yaml
exporters:
  jaeger:
    endpoint: jaeger-operator-jaeger-collector.observability:14250
    tls:
      insecure: true
  logging: {}
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
extensions:
  health_check: {}
  memory_ballast: {}
  pprof:
    endpoint: 0.0.0.0:1777
processors:
  batch: {}
  k8sattributes:
    passthrough: true
  memory_limiter:
    check_interval: 5s
    limit_mib: 1638
    spike_limit_mib: 512
  spanmetrics:
    dimensions:
      - name: namespace
      - name: pod
      - name: node
      - name: http.status_code
    dimensions_cache_size: 2000
    latency_histogram_buckets:
      - 1ms
      - 10ms
      - 100ms
      - 500ms
      - 1s
      - 10s
    metrics_exporter: prometheus
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-prometheus-receiver
          scrape_interval: 30s
          static_configs:
            - targets:
                - ${MY_POD_IP}:8888
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
    - health_check
    - memory_ballast
    - pprof
  pipelines:
    logs:
      exporters:
        - logging
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
    metrics:
      exporters:
        - prometheus
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
    traces:
      exporters:
        - jaeger
      processors:
        - batch
        - memory_limiter
        - k8sattributes
        - spanmetrics
      receivers:
        - otlp
        - jaeger
        - zipkin
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888
```
When curl opentelemetry collector's metric, I see some metric's type switch again and again(especialy kafka).
