### ISSUE TITLE
[Observ] Streamline `eventer-exporter` watched event types

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#402]

**Comment by jojotong** [comment]
Change milestone to 1.23 because it's simple.

**Comment by jojotong** [comment]
Finished at https://github.com/kubegems/plugins/commit/e016965e0bafb80d528f6bf284300158bbcbe4f4, three changes:
1. upgrate helm charts to `2.1.5` to use latest official image `v1.1.0`
2. use clusterrole created by self to replace clusterrole `view`
3. Only collect event created by these resources:
```yaml
      route:
        routes:
          - match:
            - kind: "Pod|Deployment|ReplicaSet|StatefulSet|DaemonSet"
              receiver: "dump"
```
