### ISSUE TITLE
kubegems-plugins : Reconciler error,  event runner on failed

### ISSUE THREAD

**Issue by JosonJiang** [kubegems/kubegems#71]
```
PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
----------
{"level":"error","ts":1652917167.6775742,"logger":"controller-runtime.manager.controller.installer-controller","msg":"Reconciler error","name":"kubegems-plugins","namespace":"kubegems-installer","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:302\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
{"level":"info","ts":1652917328.837031,"logger":"logging_event_handler","msg":"[playbook task]","name":"kubegems-plugins","namespace":"kubegems-installer","gvk":"plugins.kubegems.io/v1beta1, Kind=Installer","event_type":"playbook_on_task_start","job":"5743654948930018631","EventData.Name":"installer : include_tasks"}

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : include_tasks] ***********************************************
task path: /opt/ansible/roles/installer/tasks/main.yml:3
```

kubelet --version
Kubernetes v1.23.6

` kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
`
按照 https://www.kubegems.io/docs/installation/quick-install 安装  kubectl logs -n kubegems-installer  出现以上错误；
现在有集群，使用kuebadm 安装的“一主三从模式” ，后面采用 rancher 将集群导入（完全没问题），现在想使用 kubegems 导入。

`
 kubectl get node
NAME                STATUS          ROLES                           AGE        VERSION
master               Ready            control-plane,master   21d           v1.23.6
node1               Ready             node,worker                21d           v1.23.6
node2               NotReady       node                            21d           v1.23.6
ubuntu-server   Ready             node                            21d           v1.23.6

`

现在  kubegems 被调度到 node1  的

看下什么原因 谢谢了

**Comment by JosonJiang** [comment]
另外我看了下kubegems需要安装 以下组件；

```
helm      已安装v3.8.2
cert-manager  已安装
jaeger   已安装 jaegertracing/all-in-one 1.33.0
calico    已安装 v3.22.2

```
但这几个集群内 已经安装过，如果再次执行 安装会出现什么问题？

**Comment by LinkMaq** [comment]
首先，感谢使用 KubeGems 并反馈问题. 🙏

KubeGems1.20.0-beta.2 目前支持的 Kubernetes 版本为 `1.18.0 ~ 1.20.15` ，大于1.20的版本我们会在下个 release 中支持。
请用上述 k8s版本获得更好的使用体验。

> 另外我看了下kubegems需要安装 以下组件；
> 
> ```
> helm      已安装v3.8.2  (installer不会安装 helm)
> cert-manager  已安装  (installer会覆盖安装 cert-manage r1.4.0)
> jaeger   已安装 jaegertracing/all-in-one 1.33.0 (installer默认关闭 jaeger，启动后会覆盖安装jager-1.25.0<kubegems二开版本>)
> calico    已安装 v3.22.2 （installer 不会安装 calico）
>```

**Comment by JosonJiang** [comment]
`
2022-05-20 04:05:51.469 warn    config/config.go:90     no config file found
2022-05-20 04:05:51.47  info    config/config.go:107    config from env: ARGO_PASSWORD=**************
2022-05-20 04:05:51.47  info    config/config.go:107    config from env: GIT_PASSWORD=************
2022-05-20 04:05:51.47  info    config/config.go:107    config from env: MYSQL_PASSWORD=************
2022-05-20 04:05:51.471 info    config/config.go:107    config from env: REDIS_PASSWORD=************
2022-05-20 04:05:51.471 info    config/config.go:107    config from flag: jwt-cert=/certs/jwt/tls.crt
2022-05-20 04:05:51.471 info    config/config.go:107    config from flag: jwt-key=/certs/jwt/tls.key
2022-05-20 04:05:51.471 info    log/log.go:19   logger level updated    {"level": "debug"}
2022-05-20 04:05:51.472 warn    tracing/tracing.go:37   could not initialize jaeger tracer: no service name provided
2022-05-20 04:05:51.487 error   gorm@v1.21.15/gorm.go:202       failed to initialize database, got error Error 1049: Unknown database 'gemcloud'
Error: failed init dependencies: Error 1049: Unknown database 'gemcloud'
failed init dependencies: Error 1049: Unknown database 'gemcloud'

`

好的 谢谢回复，不过按最新的安装方式

`KUBEGEMS_VERSION="${KUBEGEMS_VERSION:-v1.20.0-beta.2}"
CONTAINER_RUNTIME="${CONTAINER_RUNTIME:-docker}"
REPOSITORY="${REPOSITORY:-docker.io/kubegems}"
STORAGECLASS="${STORAGECLASS:-local-path}"
CLUSTER_NAME="${CLUSTER_NAME:-kubegems-centrol}"
kubectl apply -f <( \
    wget -O - https://github.com/kubegems/installer-operator/releases/download/${KUBEGEMS_VERSION}/centrol.installer.template.yaml | \
        KUBEGEMS_VERSION="${KUBEGEMS_VERSION}" \
        CONTAINER_RUNTIME="${CONTAINER_RUNTIME}" \
        REPOSITORY="${REPOSITORY}" \
        STORAGECLASS="${STORAGECLASS}" \
        CLUSTER_NAME="${CLUSTER_NAME}" \
        envsubst \
)
`

再查看下 现在大部分 Pod 正常运行，再卸载前又一次关注下

![微信截图_20220520041308](https://user-images.githubusercontent.com/3362073/169396644-3bf2dc28-1686-40c3-8f5d-823432f263a3.png)


三个Pod 错误原因均为：
 failed to initialize database, got error Error 1049: Unknown database 'gemcloud'

祝 kubegems 越来越好，也希望我的反馈对kubegems开发有所帮助；谢谢回复，继续关注

**Comment by LinkMaq** [comment]
非常感谢您@[JosonJiang](https://github.com/JosonJiang) 详细的问题描述。令人尴尬的是，目前很多朋友在部署 kubegems 时都遇到了数据库初始化的问题。

`Unknown database 'gemcloud'`

由于 MYSQL初始化的任务位于 Ansible 最后的 **PostStart**阶段，这意味着前置 Task 中出现任何非预期的 error 都会造成任务中断（是的，kuebgems-installer 我们正在进行重构，未来会将各plugin 独立安装部署，放弃采用 ansible-operator 集中式的管理）

https://github.com/kubegems/installer-operator/blob/main/roles/installer/tasks/poststart.yaml#L159

```yaml
- name: Core Plugins | Gems Jobs
  when:
    - mode == "centrol"
    - locations == "inside"
  ignore_errors: true
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - kubegems/chartmuseum/uploader.yaml
    - kubegems/service/sqlinit.job.yaml         #运行在最后
```

目前临时的解决的方案为手动提交 `gems-mysql-initialize.job.yaml` 这个任务进行数据库初始化

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: gems-mysql-initialize
  name: gems-mysql-initialize-v1.20.0-beta.3
  namespace: gemcloud-system
spec:
  backoffLimit: 10
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: gems-mysql-initialize
      name: gems-mysql-initialize
    spec:
      restartPolicy: OnFailure
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - gems-service
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - args:
        - service
        - migrate
        - initdata=true
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: gems-secret
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: gems-secret
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: gitea-root-password
              name: gems-secret
        - name: ARGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: argo-admin-password
              name: gems-secret
        image: registry.cn-beijing.aliyuncs.com/kubegems/kubegems:v1.20.0-beta.3
        imagePullPolicy: IfNotPresent
        name: gems-mysql-initialize
        volumeMounts:
        - mountPath: /serv/certs/jwt
          name: gems-jwt-certs
      volumes:
      - name: gems-jwt-certs
        secret:
          defaultMode: 420
          secretName: gems-service-certs-secret
```

---
此外，根据之前和一些用户的排错现象上来看，目前上述现象主要集中在 KubeGems 与 Kubernetes 的版本支持上，导致 installer 部署异常中断。 可以将它的日志提交到 issues 更有助于我们分析中断原因。

```
kubectl logs -n kubegems-installer  kubegems-installer-manager-xxx
```

最后我再重复一下，在部署时还需确认使用我们推荐的 Kubernetes 版本。感谢你的祝福:heart:
