### ISSUE TITLE
CPU percentage in HPA should be based on limits.

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#87]
Kubernetes 的 HPA 在做资源计算时，采用的是 pod中的 request.cpu，在集群资源超分的情况下，我们通常会给 pod 设置一个较小的 request.cpu。但这样就会造成 HPA 在无任何负载的情况下扩容 pod。

[Horizontal Pod Autoscaler should use resource limit as its base for calculation](https://github.com/kubernetes/kubernetes/issues/72811)

当前在 kubernetes 无法解决的情况下，我们只能通过将 percentage 设置为 > 100%来解决。

考虑到在前端页面更加符合用户直觉，我们有必要调整下hpa中percentage的计算公式。

```console
percentage =  (cpu.limit  *  expect.percentage %) /  cpu.request
```  

例子：

```yaml
spec:
  container:
  - name: application
    resource:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "4"
        memory: 8Gi
```
如果一个应用的资源限制是 4C8G，那么在 KubeGems 的扩缩容中，如果按照 cpu使用率 80%扩容的话，在提交 hpa 的percentage的计算公式如下

```console
(4*1000 *0.8) / 100 = 32  = 3200%
```

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: hpa
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: default
  targetCPUUtilizationPercentage: 3200
```
